version: "3.8"
services:

  backend-server:
    image: registry.gitlab.com/librefoodpantry/training/microservices/microservices-examples/backend-for-frontend:latest
    init: true
    ports:
      - 10001:3000
    environment:
      BASE_URL: http://localhost:10001/
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

networks:
  backend-network:
