version: "3.3"
services:
  backend-server:
    image: backend-server:dev
    build: .
    # init: true
    ports:
      - 10001:3000
    environment:
      BASE_URL: http://localhost:10001/
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

  test-runner:
    image: test-runner:dev
    build: testing/test-runner
    environment:
      SUT_BASE_URL: http://backend-server:3000/
      SUT_MONGO_URL: mongodb://backend-database
      SUT_MONGO_DATABASE: items
      SUT_MONGO_COLLECTION: items
      TEST_TIMEOUT_MS: 5000
    volumes:
      - type: bind
        source: ./testing/test
        target: /app/test
        read_only: true
      - type: bind
        source: ./lib
        target: /app/lib
        read_only: true
    networks:
      - backend-network
    depends_on:
      - backend-server

networks:
  backend-network:
